name: ReactJS CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js v22
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      # Install dependencies
      - name: Install dependencies
        run: npm ci  # safer than npm install in CI

      # Run tests
      - name: Run tests
        run: npm test -- --watchAll=false  # disable watch mode in CI

      # Build project
      - name: Build project
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
